name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: Site-Passwords
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Inject password
              run: |
                echo "Before injection Check:"
                grep USERS_PLACEHOLDER index.html || echo "Placeholder missing!"
                
                # Use a different delimiter in sed and wrap the secret in single quotes to handle JSON safely
                sed -i "s#USERS_PLACEHOLDER#${{ secrets.USERS }}#g" index.html
                
                echo "After injection Check:"
                grep USERS_PLACEHOLDER index.html && echo "Failed to replace!" || echo "Successfully replaced."

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: .

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
